services:

  Training\Bundle\UserNamingBundle\Formatter\UserNameFormatter: ~

  Training\Bundle\UserNamingBundle\Provider\UserNameProvider:
    decorates: oro_locale.entity_name_provider
    arguments:
      - '@.inner'
      - Training\Bundle\UserNamingBundle\Formatter\UserNameFormatter

  Training\Bundle\UserNamingBundle\EventListener\UserViewListener:
    arguments:
      - '@oro_locale.entity_name_provider'
    tags:
      - { name: kernel.event_listener, event: oro_ui.scroll_data.before.userView, method: onUserView }

  Training\Bundle\UserNamingBundle\Twig\TrainingFormatExtension:
    public: false
    arguments:
      - Training\Bundle\UserNamingBundle\Formatter\UserNameFormatter
    tags:
      - { name: twig.extension }
