services:

  Training\Bundle\UserNamingBundle\Formatter\UserNameFormatter:
    arguments:
      - '@training_user_name_formatter_provider'

  Training\Bundle\UserNamingBundle\Provider\UserNameProvider:
    decorates: oro_locale.entity_name_provider
    arguments:
      - '@.inner'
      - '@training_user_name_formatter'

  Training\Bundle\UserNamingBundle\EventListener\UserViewListener:
    arguments:
      - '@oro_locale.entity_name_provider'
    tags:
      - { name: kernel.event_listener, event: oro_ui.scroll_data.before.userView, method: onUserView }
