services:

  Training\Bundle\UserNamingBundle\Formatter\UserNameFormatter: ~

  Training\Bundle\UserNamingBundle\Provider\UserNameProvider:
    decorates: oro_locale.entity_name_provider
    arguments:
      - '@.inner'
      - '@Training\Bundle\UserNamingBundle\Formatter\UserNameFormatter'

  Training\Bundle\UserNamingBundle\EventListener\UserViewListener:
    arguments:
      - '@oro_security.authorization_checker'
    tags:
      - { name: kernel.event_listener, event: oro_ui.scroll_data.before.userView, method: onUserView }

  Training\Bundle\UserNamingBundle\Twig\TrainingNameFormatRuntime:
    arguments:
      - '@Training\Bundle\UserNamingBundle\Formatter\UserNameFormatter'
    tags:
      - { name: twig.runtime }

  Training\Bundle\UserNamingBundle\Twig\TrainingFormatExtension:
    public: false
    tags:
      - { name: twig.extension }

  Training\Bundle\UserNamingBundle\Api\Processor\AddUserNamingExampleForGetMethods:
    arguments:
      - '@Training\Bundle\UserNamingBundle\Formatter\UserNameFormatter'
    tags:
      - {
        name: oro.api.processor,
        action: get,
        class: Training\Bundle\UserNamingBundle\Entity\UserNamingType,
        group: finalize
      }
      - {
        name: oro.api.processor,
        action: get_list,
        class: Training\Bundle\UserNamingBundle\Entity\UserNamingType,
        group: finalize
      }
